title: Obsidian Remote - Docs
description: Obsidian Remote - Docs
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings
site_author: TQ
repo_url: https://github.com/tquizzle/remote-obsidian
github_docs_folder: true
sticky_navigation: true
edit_on_github: false
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
logo: 'https://raw.githubusercontent.com/tquizzle/obsidian-remote/refs/heads/main/assets/obsidian-remote-logo.png'
site_favicon: 'https://raw.githubusercontent.com/tquizzle/obsidian-remote/refs/heads/main/assets/obsidian-remote-logo.png'